name: Jekyll Deploy

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Make sure node is installed.
        run: sudo apt-get -y install nodejs
      - name: Install md-to-pdf (NodeJS)
        run: npm i -g md-to-pdf
      - name: Generate PDF of Tietosuojaseloste
        run: md-to-pdf tietosuojaseloste.md
      - name: Build site
        uses: jerryjvl/jekyll-build-action@v1
      - name: Copy CNAME and PDF
        run:
         sudo cp CNAME build/ && sudo cp tietosuojaseloste.pdf build/
      - name: Publish site
        uses: actions-js/push@v1.3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         directory: build
         branch: gh-pages
         force: true
         commit_message: 🧪 Deploy with ${GITHUB_WORKFLOW}
