name: Jekyll Deploy

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build site
        uses: jerryjvl/jekyll-build-action@v1
      - name: Copy CNAME
        run:
         cp CNAME build/
      - name: Publish site
        uses: actions-js/push@v1.3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         author_email: ${GITHUB_ACTOR}@users.noreply.github.com"
         author_name: ${{ GITHUB_ACTOR }}
         directory: build
         branch: gh-pages
         commit_message: 🧪 Deploy with ${GITHUB_WORKFLOW}
